package com.innowise.userservice.model.entity;

import jakarta.persistence.*;
import java.time.LocalDate;
import lombok.Data;

/**
 * Card entity representing a payment card associated with a user.
 * Contains card information and references to the card owner.
 * 
 * @author tonny327
 * @version 1.0
 */
@Data
@Entity
@Table(name = "card_info")
@NamedNativeQuery(
    name = "Card.findByNumberNative",
    query = "SELECT c.* FROM card_info c WHERE c.number = :number",
    resultClass = Card.class
)
public class Card {

  /**
   * Unique identifier for the card.
   * Auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * Card number.
   * Must be unique across all cards and cannot be null.
   */
  @Column(nullable = false, unique = true)
  private String number;

  /**
   * Card holder's name.
   * Cannot be null.
   */
  @Column(nullable = false)
  private String holder;

  /**
   * Card expiration date.
   * Cannot be null.
   */
  @Column(name = "expiration_date", nullable = false)
  private LocalDate expirationDate;

  /**
   * User who owns this card.
   * Cannot be null and uses lazy loading for performance.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id", nullable = false)
  private User user;

}