package com.innowise.userservice.model.entity;
import jakarta.persistence.*;
import java.time.LocalDate;
import lombok.Data;

import java.util.List;

/**
 * User entity representing a user in the system.
 * Contains personal information and associated cards.
 * 
 * @author tonny327
 * @version 1.0
 */
@Data
@Entity
@Table(name = "users")
@NamedQuery(
    name = "User.findBySurnameNamed",
    query = "SELECT u FROM User u WHERE u.surname = :surname"
)
public class User {

  /**
   * Unique identifier for the user.
   * Auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * User's first name.
   * Cannot be null.
   */
  @Column(nullable = false)
  private String name;

  /**
   * User's last name.
   * Cannot be null.
   */
  @Column(nullable = false)
  private String surname;

  /**
   * User's birth date.
   * Cannot be null.
   */
  @Column(name = "birth_date", nullable = false)
  private LocalDate birthDate;

  /**
   * User's email address.
   * Must be unique across all users and cannot be null.
   */
  @Column(nullable = false, unique = true)
  private String email;

  /**
   * List of cards associated with this user.
   * Cascade operations will be applied to all cards when user is modified or deleted.
   */
  @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<Card> cards;
}